import Foundation

func getAnswerLimitText(for languageCode: String) -> String? {
    return letMeKnowText[languageCode]
}

var answerLimitText: [String: String] = [
    "aa": "Mi gudu wadata 100 su'ali na minti kan wannan lokaci.",
    "ab": "Аз жәлғіз ұқсау 100 сұрауны минутта қоршай аламын.",
    "af": "Ek kan slegs 100 vrae per minuut op hierdie oomblik beantwoord.",
    "ak": "Mepɛ sɛ mebɔɔ 100 akɔnɔtwe anaa ɔtwerɛ a edi wo din.",
    "am": "በዚህ ጊዜ በሰዓት 100 ጥያቄዎች ይመልሳል።",
    "an": "Nomás puedo responder 100 preguntes per minuto en ista mía.",
    "ar": "أستطيع الإجابة فقط على 100 سؤال في الدقيقة في هذا الوقت.",
    "as": "এই সময়ে আমি কেৱল ১০০ প্ৰশ্ন প্ৰতি মিনিটে উত্তৰ দিবলৈ পাৰি।",
    "av": "Ма хацӀадала гӀагӀурш 100 вопросаш минутда.",
    "ay": "Jaykasqan 100 t'ikch'urakipuni wakasqan ch'uyanchisku.",
    "az": "Mən yalnız bu vaxtda dəqiqədə 100 sualı cavablandıra bilirəm.",
    "ba": "Миңа ушын һәм ишләтмәгән вакытта миң ҡан еште.",
    "be": "На гэты момант я магу адказваць толькі на 100 пытанняў за хвіліну.",
    "bg": "Мога да отговоря само на 100 въпроса на минута в този момент.",
    "bh": "मैं इस समय प्रति मिनट केवल 100 प्रश्नों का उत्तर दे सकता हूँ।",
    "bi": "Mi save onli ansa 100 kuesten long wan minit long dispela taim.",
    "bm": "Mɛ ka kan na 100 kàsùbi ka mɛgɛ ka ku y'i kana.",
    "bn": "এই সময়ে আমি কেবল 100 প্রশ্ন প্রতি মিনিটে উত্তর দিতে পারি।",
    "bo": "སྤྱད་པའི་དུས་ཚོད་དམ་པའི་གྲོས་གཅོད་མི་འདྲ་བཤུས་ནས། ༡༠༠ འདྲ་གཅོད་གཅིག་ལས་ཤུགས་པ་དེ་ཡིན་པའི་དུས་ཚོད་ནང་བཤུས་རྐྱེན་པས།",
    "br": "N'hallin respont nemet 100 goulenn dre vunutenn d'ar mare-mañ.",
    "bs": "Mogu odgovoriti samo na 100 pitanja u minuti u ovom trenutku.",
    "ca": "Només puc respondre a 100 preguntes per minut en aquest moment.",
    "ce": "Со 100 анархийн аз гӀала дийца хьана шувала.",
    "ch": "Mague na'anai 100 chalan este na minachong este lokkuei.",
    "co": "Può rispondere solu à 100 dumande à u minutu in stu mumentu.",
    "cr": "Mikaskowâsiman 100 namôya pêyak ê-iskwêw ê-mêkwanohk atoskêyi ê-nahkawi.",
    "cs": "Dokážu odpovědět pouze na 100 otázek za minutu v tomto okamžiku.",
    "cu": "ѩ҆ а҆́гꙑ въ ми́нꙋтꙋ ꙗ҆́кѡ и҆ ҡѡ́лкꙑ дв҃а҆ сто҆ въс҃кыя ѿгл҃аго и҆ настоѧ́щагѡ си́та.",
    "cv": "Ман тытта икеҫен тып 100 сура улăшывам.",
    "cy": "Dim ond 100 cwestiwn y gallaf eu hateb y munud ar hwn.",
    "da": "Jeg kan kun besvare 100 spørgsmål pr. minut på dette tidspunkt.",
    "de": "Ich kann derzeit nur 100 Fragen pro Minute beantworten.",
    "dv": "މިހާރުގެ ދުވަހު އެއް ތިހެމަކަ 100 ފުރަތަމަށް ޖަނައިފިކޭޝަން ކަވަބާ.",
    "dz": "སྐྱད་པའི་དུས་ཚོད་དམ་པའི་གྲོས་གཅོད་མི་འདྲ་བཤུས་ནས། ༡༠༠ འདྲ་གཅོད་གཅིག་ལས་ཤུགས་པ་དེ་ཡིན་པའི་དུས་ཚོད་ནང་བཤུས་རྐྱེན་པས།",
    "ee": "Mɔ nyɔ nyuie le 100 bliboŋ bliboŋi tso ameŋ.",
    "el": "Μπορώ να απαντήσω μόνο σε 100 ερωτήσεις ανά λεπτό αυτή τη στιγμή.",
    "en": "I can only answer 100 questions per minute at this time.",
    "eo": "Mi povas respondu nur al 100 demandoj je minuto ĉi tiun fojon.",
    "es": "Solo puedo responder 100 preguntas por minuto en este momento.",
    "et": "Saan praegu vastata ainult 100 küsimusele minutis.",
    "eu": "Hemen bakarrik erantzun dezaket 100 galdera minutuko.",
    "fa": "فقط می‌توانم در این لحظه به ۱۰۰ سوال در دقیقه پاسخ دهم.",
    "ff": "Ndam def yu yaari jikko 100 nopp na loolu dem na.",
    "fi": "Voin vastata vain 100 kysymykseen minuutissa tällä hetkellä.",
    "fj": "Au rawa ni vakaqarai tiko e na gauna oqo na 100 kereiti e na dua na miniti.",
    "fo": "Eg kann bert svara 100 spurningar í minuttin nú.",
    "fr": "Je ne peux répondre qu'à 100 questions par minute pour le moment.",
    "ga": "Ní féidir liom ach 100 ceist a fhreagairt in aghaidh an nóiméad ag an am seo.",
    "gd": "Chan urrainn dhomh ach 100 ceist a fhreagairt gach mionaid aig an àm seo.",
    "gl": "Só podo responder 100 preguntas por minuto neste momento.",
    "gn": "Che ko ojeguerakuéra peteî 100 mba'epa ha minutópe ko'ãga temimbo'e.",
    "gu": "આ સમયે 100 પ્રશ્નોનો માત્ર ઉત્તર આપી શકું છું.",
    "gv": "Nagh voddym gee 100 kyshee er myn as y traa shoh.",
    "ha": "Zan iya saurara 100 tambayoyin da suka wuce minti 1 a wannan lokaci.",
    "he": "אני יכול לענות רק על 100 שאלות לדקה בזמן הזה.",
    "hi": "मैं इस समय में प्रति मिनट केवल 100 प्रश्नों का उत्तर दे सकता हूँ।",
    "ho": "Au ga'i le'u 100 kwestin long minet long taim ia.",
    "hr": "Mogu odgovoriti samo na 100 pitanja u minuti u ovom trenutku.",
    "ht": "Mwen ka reponn sèlman 100 kesyon pa minit nan moman sa a.",
    "hu": "Csak 100 kérdésre tudok válaszolni percenként ebben a pillanatban.",
    "hy": "Ես առանց խնդրելու կարող եմ միայն 100 հարցին անդամանց աջարաբեթյան։",
    "hz": "Ni wòtɔ ku dɔli 100 nwenɔ ɖi nú fɔ lɛɖi nú ŋɔ.",
    "ia": "Io posse responder solmente a 100 questiones per minuto a iste momento.",
    "id": "Saya hanya bisa menjawab 100 pertanyaan per menit pada saat ini.",
    "ie": "Me posse responder solmen a 100 questiones per minuto in iste momento.",
    "ig": "Á na-eche na mụ na-anabata 100 ndepụtara na oge ahu.",
    "ii": "ꀀꁚꀋ ꁏꂷꂷ ꀣꅏ 100 ꏏ ꂷꃅꏢ ꏓ.",
    "ik": "Niqiit ellami 100 arnassiaġaaq ullaapta.",
    "io": "Me povas respondar nur 100 demandoz per minuto aden momenti.",
    "is": "Ég get aðeins svarað 100 spurningum á mínútu í þessum stundum.",
    "it": "Posso rispondere solo a 100 domande al minuto in questo momento.",
    "iu": "ᐊᓐᓇᐅᔭᖅ ᑲᑎᓯᕋᖅᑎᒻᒪᑦ 100 ᑐᓴᖅᑲᕆᓇᖅᑐᐃᑦ ᐃᓅᒐᐅᖅᓇᖏᑦᓱᐃᑦᑕᖅᑐᐃᑦᓄᑦ ᓴᓇᙱᒃ.",
    "ja": "私はこの時点で1分あたり100の質問にしか答えることができません。",
    "jv": "Aku isih bisamel dene 100 pitakon ana menit saiki.",
    "ka": "მე შემიძლია მხოლოდ 100 კითხვა წუთში პასუხობ ამ წუთში.",
    "kg": "Nalingi kokikola to koyeba pe 100 mokomi mwa minute mwa tango ya loposo.",
    "ki": "Aũ gũtongoria magana ma 100 mũthenya ku minute iyo na ngũcio.",
    "kj": "Ndilondoka okukwarto 100 oshikwambi pokugudhi kwee temuko.",
    "kk": "Мен тек 100 сұрауға минутта жауап бере аламын, осы уақытта.",
    "kl": "Ataqatiinngilaq. 100 immaqarpoq pissutsit ataqatiinngikkaluartumik.",
    "km": "ខ្ញុំអាចឆ្លើយតែការសំនួរ 100 ក្រុមក្នុងមួយនាទីនៅពេលនេះ។",
    "kn": "ನಾನು ಈ ಸಮಯದಲ್ಲಿ ಪ್ರತಿ ನಿಮಿಷದಲ್ಲಿ 100 ಪ್ರಶ್ನೆಗಳಿಗೆ ಮಾತ್ರ ಉತ್ತರಿಸಬಹುದು.",
    "ko": "나는 현재 1분당 100개의 질문에만 답변할 수 있습니다.",
    "kr": "Nda kọrọtọ kè wá fọwọrà 100 àlápèjù ní ọ̀sán àtí kìnnì yìí.",
    "ks": "مي چه وہمتلہ روزنه زونمو اوقت زوئی لہ تنها 100 سوالونه جواب ورکړمۍ۔",
    "ku": "Ez tenê dikarim ji bo 100 pirsgirêkan li hejmarê li vê demê bersiv bidim.",
    "kv": "Вӧ сарын вариснул, мин асчын 100 башшо выд вёсьпян коз вутген.",
    "kw": "Nyns yw genev y jevo erys 100 kesstrifennow om levyr yn termyn ma.",
    "ky": "Мен тек эмне 100 суроолорго жооп бере алам салынганда.",
    "la": "Hoc tempore tantum centum quaestiones per minutum respondere possum.",
    "lb": "Ech kann nëmmen 100 Froen pro Minutt op dëser Zäit beäntweren.",
    "lg": "Nze n'olabyemu okukwatta obuzibu 100 mu kyalo kye kimu ekitundu kye leero.",
    "li": "Iech kin allein 100 vraoge per minuut beäntwerre óp dit moment.",
    "ln": "Nakoyebisa soki 100 mabele na minute te mu moninga oyo.",
    "lo": "ຂອບໃຫມ່ຂອງຂ້ອຍສາມາດຕອບເລື້ອນໄປ 100 ຄໍາຖາມຕໍາແຫນກຕໍ່ສະບາຍດີ.",
    "lt": "Šiuo metu galiu atsakyti tik į 100 klausimų per minutę.",
    "lu": "Kabikela ngibetela tu 100 butuku bua minutu buka tshibaka ulelo ubo.",
    "lv": "Es varu atbildēt tikai uz 100 jautājumiem minūtē šobrīd.",
    "mg": "Aza adika fijeriko satria 100 fanontaniana fotsiny ahoana ny menoko eo anoloan'io fotoana io.",
    "mh": "Enañ kwe ra emaanļọñ lọñ mool 100 kwōm̧ōm̧oļ koḷañ kaab mañij eo an kōn̄to.",
    "mi": "Ka taea e au te whakautu noa iho i ngā pātai 100 ā-kupu i ia meneti i tēnei wā.",
    "mk": "Можам само да одговорам на 100 прашања на минута во овој момент.",
    "ml": "ഞാൻ ഇപ്പോൾ ഒരു മിനിറ്റിൽ 100 ചോദ്യങ്ങൾക്ക് മാത്രമേ ഉത്തരം നൽകാനാകുക.",
    "mn": "Энэ хугацаанд 1 минутанд 100 асуултад хариулах боломжтой.",
    "mr": "मी ह्या वेळी 1 मिनिटात 100 प्रश्नांकितर उत्तर देऊ शकतो.",
    "ms": "Saya hanya boleh menjawab 100 soalan setiap minit pada masa ini.",
    "mt": "Nista' biss nindirizza 100 mistoqsijiet kull minuta f'din iż-żmien.",
    "my": "ကျွန်တော်တို့သည် ဤအချိန်မှာ မွေးမြူခြင်းတွင်သာ 100 မေးမြူနှင့်ပါဝါ အပါအဝင် အတွက်သာ အခြေခံရန်။",
    "na": "E akatu au ke utut i ai a hulagul ia 100 koatau i ai i dinan e.",
    "nb": "Jeg kan bare svare på 100 spørsmål per minutt akkurat nå.",
    "nd": "Ndiyakwazi ukujikeleza kuphela amaphuzu angamakhulu okuqala ngemizuzwana le.",
    "ne": "मैले यस समय १ मिनेटमा १०० प्रश्नको मात्र उत्तर दिन सक्दैन।",
    "ng": "Mbe ñu kunyandza ko 100 tinhlamulo lerin'wesiku ra loko.",
    "nl": "Ik kan op dit moment slechts 100 vragen per minuut beantwoorden.",
    "nn": "Eg kan berre svara på 100 spørsmål per minutt akkurat no.",
    "no": "Jeg kan bare svare på 100 spørsmål per minutt akkurat nå.",
    "nr": "Ngiyakwazi ukujikeleza kuphela amaphuzu angamakhulu okuqala ngemizuzwana le.",
    "nv": "K'éí łaak dootł'izhígíí hozhogo yiiltł'id doo késhgiizh yiyiiltł'id daaztsaii at'éego bee.",
    "ny": "Ndinakuphawuleni mafungulo 100 m'mizinda yaboma pa nthawi imenei.",
    "oc": "Pòdi respondre solament a 100 questions per minuta ara.",
    "oj": "Niwi nwi naawenimaa 100 maajaat aanokshii imaa.",
    "om": "Kan inni ola jechuun miidhaan 100n dirqama kabira jedhu akka ta'e ni danda'u.",
    "or": "ମୁଁ ଏହି ସମୟରେ ପ୍ରতি ମିନିଟ୍‌ରେ 100 ପ୍ରଶ୍ନ ଜବା ଦେଇ ପାରୁ।",
    "os": "Сæгд стыри 100 хатыуадзы буруд фындз кæнджылауыты ырыстыу.",
    "pa": "ਮੈਂ ਇਸ ਸਮੇਂ ਹਰ ਮਿੰਟ ਵਿੱਚ ਸਿਰਫ 100 ਸਵਾਲਾਂ ਦਾ ਜਵਾਬ ਦੇ ਸਕਦਾ ਹਾਂ।",
    "pi": "इमं वेलं एकसमये 100 प्रस्नान परिषीयं मम जवानमि।",
    "pl": "Mogę odpowiadać tylko na 100 pytań na minutę w tym momencie.",
    "ps": "زه دغه وخت کړم چې د منځپانګلې په منټ کې 100 پوښتنې ځواب کړم.",
    "pt": "Só posso responder a 100 perguntas por minuto neste momento.",
    "qu": "Mana Waranqa! 100 willaykuna yupaychankuqa kay.",
    "rm": "Nova Sessiun. Fai Tap per Parlar.",
    "rn": "Sesyon Nuvèl. Pousé Pou Pale.",
    "ro": "Sesiune Nouă. Atingeți pentru a Vorbi.",
    "ru": "Новая Сессия. Коснитесь, чтобы Говорить.",
    "rw": "Sesheni Nshya. Gusaba Kwandika.",
    "sa": "नवा सत्र. बोलनको लागि ट्याप गरा.",
    "sc": "Sessión Nova. Clichia pro faeddare.",
    "sd": "نئي ڏورو. ٽيپ ڪرڻ لاءِ ڪريو.",
    "se": "Oažžut Session. Tappat Dahkat.",
    "sg": "Séans Nau. Tòke pa Palé.",
    "si": "මම මෙතනින් අතර 100 ප්‍රශ්න 1 වන කාලයේදී පිළිතුරු සාදන හැක.",
    "sk": "Môžem odpovedať len na 100 otázok za minútu v tomto čase.",
    "sl": "Lahko odgovorim samo na 100 vprašanj na minuto ob tem času.",
    "sm": "E fai tele faʻalilolilo 100 o nuʻu i le minite nei i taimi nei.",
    "sn": "Ndinoratidza chido chekuenda kune 100 maitiro kune minda yekupedzisira uye kuzvitakura mu minute iyi.",
    "so": "Waxaan kaliya jawaabi kartaa 100 su'aal kasta oo daqiiqaddan waqtigaan.",
    "sq": "Mund të jap përgjigje vetëm për 100 pyetje në minutën në këtë kohë.",
    "sr": "Могу само одговорити на 100 питања у минуту у овом тренутку.",
    "ss": "Ngiyakwazi ukujabula kuphela ngezigaba ezingu-100 ngemizuzu kulendlela.",
    "st": "Ke ka ba nako eo ke ka ba ka sebelisa ho jesa lipatlisiso tsa 100 ka molemo.",
    "su": "Abdi Duaan Lamun 100 Peryogi Ka Menit Ieu Pisan Sawaktos Ieu.",
    "sv": "Jag kan bara svara på 100 frågor per minut just nu.",
    "sw": "Naweza kujibu maswali 100 kwa dakika wakati huu.",
    "ta": "இந்த நேரத்தில் ஒரு நிமிடத்தில் 100 கேள்விகளுக்கு மட்டும் பதில் சொல்ல முடியும்.",
    "te": "ఈ సమయంలో ఒక నిమిషంలో 100 ప్రశ్నలకు మాత్రమే సమాధానం ఇచ్చుకున్నాను.",
    "tg": "Ман танҳо ба сад 100 савол дар дақиқаи ҳол дада метавонам.",
    "th": "ฉันสามารถตอบคำถามได้เพียง 100 คำถามต่อนาทีในเวลานี้เท่านั้น.",
    "ti": "ኣብ ዚኸ ሰዓት፡ 100 ጥዕናውነት ንላዕሊ ብናን መንገዲ ንስኻባትን ብድዩ ትንግስቲ ቀረብ።",
    "tk": "Men şu wagtda hemme bilyaç sowala 100 jowap bermäge dikmek.",
    "tl": "Maari lamang akong sumagot ng 100 tanong kada minuto sa panahong ito.",
    "tn": "Ngiyaqonda kuphela imibuzo engu-100 ngeminithi ngalesikhathi.",
    "to": "ʻOku ou ʻi he langi ke tali pe 100 fekumi ʻo e ʻinasi ko e taimi ni.",
    "tr": "Şu anda dakikada sadece 100 soruya cevap verebilirim.",
    "ts": "Ndza tiva kahle swi endlani ku sukela swesati swa 100 eminithini hi xikongomelo lexi.",
    "tt": "Män häl yılda yalnız 100 sualağa cavap beräyem.",
    "tw": "Nkpụrụ aka akwadọm 100 aka ukwụta na itoolu a.",
    "ty": "ʻUa here ʻia naʻe teie hōʻa ʻuʻu 100 nīnau i kēia manawa.",
    "ug": "مەن تەنىلە تەن 100 سوئالغا جاۋاب بېرەمەن.",
    "uk": "Я можу відповісти лише на 100 запитань на хвилину на даний момент.",
    "ur": "میں صرف اس وقت 100 سوالوں کا جواب دے سکتا ہوں۔",
    "uz": "Men faqat ushbu vaqtda daqiqaiga 100 savolga javob beraman.",
    "ve": "Ndza swi vula xibalo lexi nga endla ku sukela masiku ma 100 eka ndhawu leyi.",
    "vi": "Tôi chỉ có thể trả lời 100 câu hỏi mỗi phút vào thời điểm này.",
    "vo": "Lafet ikam za lulik plo gebanlik 100 klodo ob klok balmi.",
    "wa": "Nén pô dji n' rèsponde k' à 100 qwèstions à l' minutnut asteure.",
    "wo": "Noppina rekk mi 100 suñu am na kàddu benn boppam.",
    "xh": "Ndiya kugqiba kuphela 100 imibuzo ngemizuzu kulesikhathi.",
    "yi": "Ikh ken nor antviklen af 100 frages per minut aynz bai dis tsayt.",
    "yo": "Mo le gba igbese kan 100 aworan ni osan na aye yi.",
    "za": "Gaux meuz goeuw 100 vuzdol goeuw maag doeuhr goeuw.",
    "zh": "我只能在这个时候每分钟回答100个问题。",
    "zu": "Ngifuna ukujabulisa kuphela izibalo ezingu-100 ngemizuzwana ngesikhathi."
]
