import Foundation

func getGreetingText(for languageCode: String) -> String? {
    return greetingText[languageCode]
}

let greetingText: [String: String] = [
    "aa": "Hey",
    "ab": "Агәди",
    "af": "Haai",
    "ak": "Hey",
    "am": "ሀይ",
    "an": "Ola",
    "ar": "مرحبًا",
    "as": "হৈ",
    "av": "Гой",
    "ay": "¡Jichha!",
    "az": "Salam",
    "ba": "Салам",
    "be": "Прывітанне",
    "bg": "Здравей",
    "bh": "नमस्कार",
    "bi": "Hey",
    "bm": "I ni sogoma",
    "bn": "হ্যালো",
    "bo": "བཀྲ་ཤིས་",
    "br": "Salut",
    "bs": "Zdravo",
    "ca": "Hola",
    "ce": "Салам",
    "ch": "Hafa adai",
    "co": "Bonghjornu",
    "cr": "Tânisi",
    "cs": "Ahoj",
    "cu": "Здравѣйте",
    "cv": "Шу",
    "cy": "Helo",
    "da": "Hej",
    "de": "Hallo",
    "dv": "ދެހެލެ",
    "dz": "རི་བོ",
    "ee": "Nenyhe",
    "el": "Γειά σας",
    "en": "Hey",
    "eo": "Saluton",
    "es": "Hola",
    "et": "Tere",
    "eu": "Kaixo",
    "fa": "سلام",
    "ff": "Hej",
    "fi": "Hei",
    "fj": "Bula",
    "fo": "Halló",
    "fr": "Salut",
    "fy": "Hallo",
    "ga": "Dia dhuit",
    "gd": "Hàlo",
    "gl": "Ola",
    "gn": "Avei",
    "gu": "હાય",
    "gv": "Shoh",
    "ha": "Sannu",
    "he": "שָׁלוֹם",
    "hi": "नमस्ते",
    "ho": "Hai",
    "hr": "Bok",
    "ht": "Alo",
    "hu": "Helló",
    "hy": "բարև",
    "hz": "Hai",
    "ia": "Salute",
    "id": "Halo",
    "ie": "Salute",
    "ig": "Ndewo",
    "ii": "니하오",
    "ik": "Hai",
    "io": "Saluto",
    "is": "Hæ",
    "it": "Ciao",
    "iu": "ᐃᓄᒃᑎᑐᑦ",
    "ja": "こんにちは",
    "jv": "Hai",
    "ka": "გამარჯობა",
    "kg": "Mbote",
    "ki": "Hai",
    "kj": "Hai",
    "kk": "Сәлеметсіздер",
    "kl": "Aluu",
    "km": "ជំរាបសួរ",
    "kn": "ಹಲೋ",
    "ko": "안녕하세요",
    "kr": "Hai",
    "ks": "ہیلو",
    "ku": "Silav",
    "kv": "Сават",
    "kw": "Dydh da",
    "ky": "Салам",
    "la": "Salve",
    "lb": "Moïen",
    "lg": "Yaa",
    "li": "Hoi",
    "ln": "Mbote",
    "lo": "ສະບາຍດີ",
    "lt": "Labas",
    "lu": "Mbote",
    "lv": "Sveiki",
    "mg": "Mbola tsara",
    "mh": "Yokwe",
    "mi": "Haere mai",
    "mk": "Здраво",
    "ml": "ഹലോ",
    "mn": "Сайн уу",
    "mr": "नमस्कार",
    "ms": "Hai",
    "mt": "Bongu",
    "my": "ဟယ်လို",
    "na": "Hello",
    "nb": "Hei",
    "nd": "Hai",
    "ne": "नमस्कार",
    "ng": "Hello",
    "nl": "Hallo",
    "nn": "Hei",
    "no": "Hei",
    "nr": "Hai",
    "nv": "Yá'át'ééh",
    "ny": "Muli bwanji",
    "oc": "Salut",
    "oj": "Aaniin",
    "om": "Akkam",
    "or": "ହଲୋ",
    "os": "Салам",
    "pa": "ਹੈਲੋ",
    "pi": "नमस्ते",
    "pl": "Cześć",
    "ps": "سلام",
    "pt": "Olá",
    "qu": "Rimaykullayki",
    "rm": "Bun di",
    "rn": "Hej",
    "ro": "Salut",
    "ru": "Привет",
    "rw": "Mwaramutse",
    "sa": "नमस्कार",
    "sc": "Ciao",
    "sd": "هيلو",
    "se": "Hei",
    "sg": "Boungu",
    "si": "හෙයි",
    "sk": "Ahoj",
    "sl": "Zdravo",
    "sm": "Talofa",
    "sn": "Mhoroi",
    "so": "Haddii aad tihiin",
    "sq": "Përshëndetje",
    "sr": "Здраво",
    "ss": "Sawubona",
    "st": "Hei",
    "su": "Hai",
    "sv": "Hej",
    "sw": "Hodi",
    "ta": "ஹலோ",
    "te": "హలో",
    "tg": "Салом",
    "th": "สวัสดี",
    "ti": "ሰላም",
    "tk": "Salam",
    "tl": "Kamusta",
    "tn": "Hei",
    "to": "Mālō e lelei",
    "tr": "Merhaba",
    "ts": "Hei",
    "tt": "Салам",
    "tw": "Aane",
    "ty": "Ia orana",
    "ug": "ياخشىمۇسىز",
    "uk": "Привіт",
    "ur": "ہیلو",
    "uz": "Salom",
    "ve": "Hei",
    "vi": "Xin chào",
    "vo": "Tavut",
    "wa": "Djohow",
    "wo": "Nopp naa la",
    "xh": "Molo",
    "yi": "העלא",
    "yo": "Bawo ni",
    "za": "Ndvaa",
    "zh": "你好",
    "zu": "Sawubona"
]
