import Foundation

func getLetMeKnowText(for languageCode: String) -> String? {
    return letMeKnowText[languageCode]
}

let letMeKnowText: [String: String] = [
    "aa": "Fainyie ŋmɛ anaa m'asan de akyi",
    "ab": "Ауылым һыу басма?",
    "af": "Laat weet my wat om meer te sê!",
    "ak": "Mema mo na menyɛ bɛkasa abɛyɛ ase!",
    "am": "እማማ ያስገባሻል ምን ማስታወሻ!",
    "an": "Dizme qué decir más dica!",
    "ar": "أخبرني بماذا أقول المزيد عنه!",
    "as": "আমি আৰু কি সোনামুনি বলক বলিবলৈ বুজো!",
    "av": "Ма ку сӀун соган къовас, чӀан кІапи ярис!",
    "ay": "Nayra qhati ukamawa phanqa!",
    "az": "Mənə daha çox nə deyəcəyimi bildirin!",
    "ba": "Мине ки билгеләй килеп итерсең!",
    "be": "Скажыце мне, што яшчэ сказаць!",
    "bg": "Кажете ми какво още да кажа!",
    "bh": "मला काही एक बोलायला सांगा!",
    "bi": "Lem mi laet nao wea bae mi talem moa!",
    "bm": "Môgô bɛ kô fɔ yɛlɛ mɔgô ko!",
    "bn": "আমাকে জানান আরও কী বলতে হবে!",
    "bo": "ངེས་འབྲེལ་མེད་འཛུག དང་ ལག་པར་བྱས་བཟོས་བཏང་པོ་!",
    "br": "Lakaat deomp gouzout petra lâroutiñ oan!",
    "bs": "Reci mi šta još reći!",
    "ca": "Digues-me què més dir!",
    "ce": "Со ма йолуш декъаш доц дилакъ!",
    "ch": "Ti enao hu setbisio!",
    "co": "Dimmi cio che dici di più!",
    "cr": "ᓂᐢᑕᐣ᙮ ᓂᐢᑕᐣ᙮ ᓂᐢᑕᐣ᙮",
    "cs": "Řekněte mi, co mám říct víc!",
    "cu": "Скажи ми что и рѣчи еще!",
    "cv": "Сăма те çун çогăн тăват, пăрçе çитай çуван!",
    "cy": "Rhowch wybod i mi beth i'w ddweud mwy amdano!",
    "da": "Lad mig vide, hvad jeg skal sige mere om!",
    "de": "Lass mich wissen, worüber ich noch sprechen soll!",
    "dv": "މިއަދަ ދައިވެސް ފެކޭދެ އަހަރެއް ފުރިންނަށް ބަދަކަށް!",
    "dz": "ངེས་པར་འོད་གཞུངས། ངེས་པར་འོད་གཞུངས། ངེས་པར་འོད་གཞུངས།",
    "ee": "Ebene nina wo fɔm kɛse ma me!",
    "el": "Πείτε μου τι άλλο να πω!",
    "en": "Let me know what to say more about!",
    "eo": "Diru al mi, kion pli diri!",
    "es": "Dime qué más decir!",
    "et": "Ütle mulle, mida veel öelda!",
    "eu": "Esan ezazu nire buruz gehiago esateko zer!",
    "fa": "به من بگو چه بگویم بیشتر!",
    "ff": "Noppata min ki mitä sano seereen!",
    "fi": "Kerro minulle, mitä sanoa enemmän!",
    "fj": "Na vakarautaka me' u tukuna mai vakasaurarara!",
    "fo": "Lat meg vita hvað ég á að segja meira um!",
    "fr": "Dites-moi quoi dire de plus!",
    "fy": "Lit my witte wat ik sizze mei!",
    "ga": "Inis dom céard eile a rá!",
    "gd": "Innisdh dhomh dè bu chòir dhomh bruidhinn!",
    "gl": "Dime que máis dicir!",
    "gn": "Mba'éicha akóĩ jasypoipy ñañoñe'ẽ!",
    "gu": "મને જણાવો કે મારી વાત વધુ શું હોય!",
    "gv": "Gow my gra dy lhiggeyrtys dou glass!",
    "ha": "Jinkane min me meya yayi amfani da magana koƙari!",
    "he": "ספר לי מה לומר עוד!",
    "hi": "मुझे बताएं कि और क्या कहना है!",
    "ho": "Tok hilo ni karabao hao kau fasi.",
    "hr": "Recite mi što još reći!",
    "ht": "Di m kisa dwe di plis sou li!",
    "hu": "Mondj nekem, mit mondjak még!",
    "hy": "Գրանցեք ինձ, թե ինչպես ավելի շատ ասել!",
    "hz": "Yehel mami nda vese voti ehe.",
    "ia": "Dicte me lo que dire plus!",
    "id": "Beritahu saya apa yang harus saya katakan lebih banyak!",
    "ie": "Ditel me lo que dire plus!",
    "ig": "Kwụsị m gị banyere gị kedu i chọrọ!",
    "ii": "ꆇꉙꉙꇴꆋ ꆇꉙꉙꇴ!",
    "ik": "Aş yax̂aaqlıq lavkenaqakuġun?",
    "io": "Diku me qua dire plu!",
    "is": "Láttu mig vita hvað ég á að segja meira um!",
    "it": "Dimmi cosa dire di più!",
    "iu": "ᐃᓯᐊᓚᐃᔨ ᐃᓅᑲᓂᔨᒃ ᓯᕙᑕᑦᑎ!",
    "ja": "もっと何を言えばいいか教えてください！",
    "jv": "Nyebutake aku apa anahe?",
    "ka": "გთხოვთ, შემიტანეთ რა ვითარდება!",
    "kg": "Tatila min ne inga ke sebisa mi!",
    "ki": "Kwambĩ mwaratana nĩkũhithĩrie nĩ ũtona!",
    "kj": "Yitu wa n'de kuzindya na!",
    "kk": "Маған қандай қосымша не десеуге айтыңыз!",
    "kl": "Sut uani una oqaatsinermik?",
    "km": "និយាយមកកម្មវិធីតួនាទី!",
    "kn": "ನನಗೆ ಇನ್ನೂ ಏನು ಹೇಳಬೇಕೆಂದು ಹೇಳಿ!",
    "ko": "더 어떻게 말해야 할지 알려주세요!",
    "kr": "Ndiî kumpi ye nko ndû yēgê?",
    "ks": "موزه چھواز دي مياں ژاندع ده وطن؟",
    "ku": "Min ji we re behsa tişta kuştina!",
    "kv": "Ка жанам дой кокиш олез?",
    "kw": "Medhowgh my a leverel dhe vos!",
    "ky": "Маа кандай башка нерсе айтуу керек деп айтыңыз!",
    "la": "Dic mihi quid amplius dicam!",
    "lb": "Sotzt mer, wat ech méi soen!",
    "lg": "Onyweza nsonyi zokwambala!",
    "li": "Laot mich weite wat ich nog sjouwe soll!",
    "ln": "Bomoi ngai ndépenda na!",
    "lo": "ພວກເຮົາວອນນີ້ຂ້າພະເຈົ້າຈະສົ່ງຂ້າພະເຈົ້າຈາກຫມາຍເກີ!",
    "lt": "Pasakyk man, ką dar turiu pasakyti!",
    "lu": "Lukolosa bua nsompi bonso!",
    "lv": "Pateiciet man, ko vēl teikt!",
    "mg": "Atsorovy ahy inona azoko atao!",
    "mh": "Majōl māl men ko ilo ej jiban?",
    "mi": "Kī mai ki ahau he aha te mea e kōrero atu ai!",
    "mk": "Кажете ми што уште да кажам!",
    "ml": "എനിക്ക് കൂടുതല്‍ എന്താണ് പറയേണ്ടതെന്ന് അറിയിക്കുക!",
    "mn": "Би юу гэхэд дагаад байна вэ?",
    "mr": "मला सांगायला काही आहे का?",
    "ms": "Beritahu saya apa yang perlu saya katakan lagi!",
    "mt": "Għiduli x'għandni ngħid aktar dwaru!",
    "my": "ကျွန်မသို့ ဘာတွေကို ပြောင်းရန် သိရသင့်သည်!",
    "na": "Nam likae deh bahsidi",
    "nb": "La meg vite hva jeg skal si mer om!",
    "nd": "Ndisitsha ngani ndiphathe kanjani!",
    "ne": "मलाई कसले कसरि बोल्नुपर्छ भन्नुहुन्छ भन्नुहोस्!",
    "ng": "Funsani inu chomwe ndidziti zambiri!",
    "nl": "Laat me weten waarover ik meer kan praten!",
    "nn": "Lat meg vite kva eg skal seie meir om!",
    "no": "La meg vite hva jeg skal si mer om!",
    "nr": "Njani ndizokukhuluma kakhulu!",
    "nv": "Díí baa ałchísiidii yaaztłi?",
    "ny": "Funsani inu chomwe ndidziti zambiri!",
    "oc": "Ditz-me çò que dire de mai!",
    "oj": "Nishkad ezhni ogenimaad zhingak!",
    "om": "Fayyadama warqee kee bara waaqa qaata?",
    "or": "ମୁଁ ଆମକୁ ଆଣିଓ କଣ କହିବା ଲାଗୁଛି!",
    "os": "Дугъарымад, ам магӀархъуи?",
    "pa": "ਮੈਨੂੰ ਦਸੋ ਕਿ ਹੋਰ ਕੀ ਕਹਿਣਾ ਚਾਹੀਦਾ ਹੈ!",
    "pi": "मामको उपायदी संवाद उपलब्ध्युत्तराणि!",
    "pl": "Powiedz mi, o czym jeszcze powiedzieć!",
    "ps": "زه به منلی څه نور څنګه ده!",
    "pt": "Diga-me o que mais devo dizer!",
    "qu": "Mananichuqa nispa kani!",
    "rm": "Di ensemma me ins bains discur!",
    "rn": "Ndukangure ko ntabona umwanya mwiza?",
    "ro": "Spune-mi ce să mai spun!",
    "ru": "Скажите мне, что еще сказать!",
    "rw": "Mfate ko nko mbona nkora cyane cyane!",
    "sa": "उपनी बाण बिनिमयज्ञमस्य कथय!",
    "sc": "Contami candu a poddat ammajare!",
    "sd": "مونهنجي کي اور ڪيا چيء چيء ڪان پوءَنديندڙ آهي!",
    "se": "Álohttak dan eará beaivválaš giela lea goit!",
    "sg": "Ha nga khumelwa nyina o tsha kumbuka nyinyi!",
    "si": "මම කුමුද කොලෝද කියනවා එයන්ට මදක්!",
    "sk": "Povedzte mi, čo ešte povedať!",
    "sl": "Povej mi, kaj naj rečem več!",
    "sm": "Faamolemole lo'u galuega!",
    "sn": "Ndinonzi ndichida kunzwisisa chokuti ndisei!",
    "so": "Mahadsanid waxaad iimeedayaan inaan ku hadlo kuwan daawada!",
    "sq": "Më tregoni çfarë të them më shumë!",
    "sr": "Кажите ми шта још рећи!",
    "ss": "Ngiyacela ubufuna ukuthi angikuthumele ntoni okushoyo kakhulu!",
    "st": "Hloka ho bolela hore ke hore efe ke efe!",
    "su": "Kumaha carana pikeun diucapkeun deui!",
    "sv": "Låt mig veta vad jag ska säga mer om!",
    "sw": "Nisaidie niseme nini zaidi!",
    "ta": "இன்னும் என்ன சொல்கின்றன என்று எனக்கு தெரியுங்கள்!",
    "te": "నాకు మరింత ఏమును చెప్పాలని చెప్పు!",
    "tg": "Ба ман гуфтан, чӣ дигар бояд гуфт!",
    "th": "บอกฉันว่าควรจะพูดอะไรมากกว่านี้!",
    "ti": "እዚኦም ንደዊስ ምስ ወዲ ምስ ብክሃምስ!",
    "tk": "Meni başga nähili gürrüňdeseňiz diňeň!",
    "tl": "Itanong mo sa akin kung ano pa ang dapat kong sabihin!",
    "tn": "Tloba ke ho bulela ho thonkana?",
    "to": "Fkai aki koe u fai kimautolu!",
    "tr": "Bana ne hakkında daha fazla ne söylemem gerektiğini söyle!",
    "ts": "Ndza ku khensa ndza ku vula leswaku hi vula va le mina!",
    "tt": "Ми өшегез исемек кайтаргыч ике?",
    "tw": "Ka afa me toɔ na mɛka me nyansa baako!",
    "ty": "Di mwa cki ci de",
    "ug": "مەن تەنبەك ياكى ئىلمەكچىنى كىم كۆرسەتمەكچى بولسىمۇ قانداق قايلغانمۇ؟",
    "uk": "Скажіть мені, що ще сказати!",
    "ur": "مجھے بتائیں کہ میں کیا اور کہاں بولوں!",
    "uz": "Meni qanday qo'shiq niqora aytsam bo'ladi?",
    "ve": "Vhe ndo unzulu na!",
    "vi": "Hãy cho tôi biết phải nói gì thêm!",
    "vo": "Difit me votik votikinü?",
    "wa": "Rexhemez-mwè k' sakê!",
    "wo": "Jàng kaw dama melni!",
    "xh": "Ndiyacela undifumanele kwaye ndiyamazi kutheni ndikufunele ukusebenzisa ntoni!",
    "yi": "זאָגט מיר, וואָס זאָל איך אייך נאָך זאָגן!",
    "yo": "Bó ṣènì mò lówó sì?",
    "za": "Gwengz laswnz quonx mih bwaecwzyz!",
    "zh": "告诉我还要说什么！",
    "zu": "Ngicela unginikeze kube lula ukuthi ngiqalelele ntoni!"
]
