import Foundation

//func getSayMoreText(for languageCode: String) -> String? {
//    return sayMoreText[languageCode]
//}

let sayMoreText: [String: String] = [
    "aa": "Haddii aad i sheegto",
    "ab": "Афыгә ацамаара арга",
    "af": "Vertel my meer",
    "ak": "Ka bi me de",
    "am": "ተው ያሉትን እያሳዩ",
    "an": "Dígame más",
    "ar": "قل لي المزيد",
    "as": "আৰু কোনো কিছু কওঁক",
    "av": "Ӏазан а малъара",
    "ay": "Qhamphimpi wasi",
    "az": "Mənə daha çox deyin",
    "ba": "Ҡайсысында аҡырыу ҡу",
    "be": "Скажыце мне больш",
    "bg": "Кажете ми още",
    "bh": "मुझे और बताओ",
    "bi": "Hau tell i go",
    "bm": "Dɔɔni kan",
    "bn": "আরও বলুন",
    "bo": "སྟོན་པའི་ངོས་འཛིན་འབད",
    "br": "Lavaretoc'h deoc'h",
    "bs": "Reci mi još",
    "ca": "Digues-me'n més",
    "ce": "Дийцара бийлахара",
    "ch": "Lepilu i sem",
    "co": "Dì mè di più",
    "cr": "Niweyiw ayanan",
    "cs": "Řekni mi víc",
    "cu": "Мⷢли ми виⷡи",
    "cv": "Чĕнеки тулыват",
    "cy": "Dywedwch fwy amdanaf",
    "da": "Fortæl mig mere",
    "de": "Erzähl mir mehr",
    "dv": "ކަނބަލު ކުރޭ",
    "dz": "ཁྱེད་ཀྱི་ངོས་འཛིན་འབད",
    "ee": "Kpe ŋutɔŋ le mɛ",
    "el": "Πες μου περισσότερα",
    "en": "Tell me more",
    "eo": "Diru al mi pli",
    "es": "Cuéntame más",
    "et": "Räägi mulle rohkem",
    "eu": "Kontatu gehiago",
    "fa": "بیشتر بگو",
    "ff": "Noppin ma",
    "fi": "Kerro minulle lisää",
    "fj": "Tukuna sobu ga me",
    "fo": "Sig mær meira",
    "fr": "Dis-moi en plus",
    "fy": "Fertel my mear",
    "ga": "Inis dom tuilleadh",
    "gd": "Innsibh dhomh barrachd",
    "gl": "Contar máis",
    "gn": "Tete ramo ojejapo",
    "gu": "વધુ કહો",
    "gv": "Lhaih lhiam dy chooilley red",
    "ha": "San ba ni",
    "he": "ספר לי עוד",
    "hi": "और बताओ",
    "ho": "Tuk mi moa",
    "hr": "Reci mi još",
    "ht": "Di m 'plis",
    "hu": "Mondd el nekem",
    "hy": "Խոսքիդ ավելին",
    "hz": "Tika moanagi o mose",
    "ia": "Dic me plus",
    "id": "Kasih tahu saya lebih banyak",
    "ie": "Dise me plu",
    "ig": "Kpọtara m aka",
    "ii": "ꑌꆪ꒝ꐻ ꑴꆸ",
    "ik": "Puniq nallunritaa",
    "io": "Priparolu plu",
    "is": "Segðu mér meira",
    "it": "Dimmi di più",
    "iu": "ᐃᓄᐃᑦᑎᐊᑦ ᓱᓇᒪᒋᒋᑦ",
    "ja": "もっと教えて",
    "jv": "Punten aku luwih",
    "ka": "მეტი თქვენ ვთქვან",
    "kg": "Nsɛ̌n'ga wɛ̌ ŋga ye bɔli",
    "ki": "Rugutha ici",
    "kj": "Hu zai na yi",
    "kk": "Маған көбірек сөйле",
    "kl": "Kikkut assi",
    "km": "ប្រាប់ខ្ញុំច្រើនមួយទៀត",
    "kn": "ಹೆಚ್ಚು ಹೇಳಿ",
    "ko": "더 말해봐",
    "kr": "Rido doo mo",
    "ks": "ونهم کہچن ژھی",
    "ku": "Min gotinên zêde bikin",
    "kv": "Сынажылой нылсоз",
    "kw": "Rag ow més",
    "ky": "Менин жаным сөйлө",
    "la": "Dic mihi amplius",
    "lb": "Sot mer méi",
    "lg": "Ogamba okutuuka",
    "li": "Vertel mich mier",
    "ln": "Loboko mobimba ebele",
    "lo": "ພວກເຂົ້າສູ້ອນ",
    "lt": "Pasakyk man daugiau",
    "lu": "Kolemba shabe",
    "lv": "Pastāstiet man vairāk",
    "mg": "Hitaova anao ho hitanareo",
    "mh": "Nen ke im imwij etal",
    "mi": "Whakamārama mai ki a au",
    "mk": "Кажи ми повеќе",
    "ml": "കൂടുതൽ പറഞ്ഞ്",
    "mn": "Бидэнд илүү хэлэх",
    "mr": "आणखी द्या",
    "ms": "Beritahu saya lebih",
    "mt": "Għidli aktar",
    "my": "ပိုမနိုင်",
    "na": "Dipan kamole",
    "nb": "Fortell meg mer",
    "nd": "Taura kuno",
    "ne": "म पनि भन",
    "ng": "Khumbula mina kakhulu",
    "nl": "Vertel me meer",
    "nn": "Fortel meg meir",
    "no": "Fortell meg mer",
    "nr": "Taura kuno",
    "nv": "Dibééhózin dóó náánátsʼaahígíí",
    "ny": "Tawonga ndi ine",
    "oc": "Ditz me mai",
    "oj": "Aandi zho niin",
    "om": "Dubbi inni guutu",
    "or": "ଆମକୁ ଆଣିବା",
    "os": "Доны ицарон",
    "pa": "ਹੋਰ ਦੱਸੋ",
    "pi": "पुढ़े बोले",
    "pl": "Powiedz mi więcej",
    "ps": "زیاتر وویل",
    "pt": "Conte-me mais",
    "qu": "Asquy ñuqa",
    "rm": "Di pli",
    "rn": "Ndi twagiye",
    "ro": "Spune-mi mai mult",
    "ru": "Расскажи мне больше",
    "rw": "Tanga ibigisha",
    "sa": "भवतु मे पुनः",
    "sc": "Aciagi a mègius",
    "sd": "اهون ڄاڻو",
    "se": "Dalle sáhtát",
    "sg": "Lekele ma nzila",
    "si": "මම තවත් ඉන්නවා",
    "sk": "Povedz mi viac",
    "sl": "Povej mi več",
    "sm": "Fa'afetai e fa'apefea",
    "sn": "Mweya kundinyora",
    "so": "Nagaa adigu leeyahay",
    "sq": "Më thuaj më shumë",
    "sr": "Кажи ми још",
    "ss": "Thumelela sengikhulume",
    "st": "Mong lemong oa ka u be ho hlahisa",
    "su": "Ceuk da puguh",
    "sv": "Säg mer mer",
    "sw": "Niambie zaidi",
    "ta": "மேலும் சொல்லு",
    "te": "మళ్లీ చెప్పండి",
    "tg": "Ман боз меарсам",
    "th": "บอกฉันมากขึ้น",
    "ti": "ሓዲሽ ክትምአይ",
    "tk": "Meniň üçin hasaplaň",
    "tl": "Sabihin mo sa akin ang karagdagang impormasyon",
    "tn": "Nkabe ka hore ho bua",
    "to": "'Osi ke tau fakakaukau",
    "tr": "Daha fazla söyle",
    "ts": "Ni vono vondzela vhavenda",
    "tt": "Миңа ярымынча айтыр",
    "tw": "Se eye more",
    "ty": "Di moi plis",
    "ug": "مەنىڭ ۋە بىلدىرىڭ",
    "uk": "Розкажіть мені більше",
    "ur": "مجھے زیادہ بتائیں",
    "uz": "Менга кўпроқ айтинг",
    "ve": "Ni dzhavuko",
    "vi": "Nói thêm cho tôi",
    "vo": "Kivomäd at",
    "wa": "Diz me pus",
    "wo": "Nopp na la",
    "xh": "Sithumelele ukuze ndikhulume",
    "yi": "זאָג מיר מער",
    "yo": "So mi lọ síwájú",
    "za": "Hwengz zeq",
    "zh": "告诉我更多",
    "zu": "Ngicela ungiphendule kakhulu",
]


