import Foundation

func getNetworkErrorText(for languageCode: String) -> String? {
    return networkErrorText[languageCode]
}

let networkErrorText: [String: String] = [
    "aa": "Maal jira internettaa.",
    "ab": "Аицәабзеиш ара алар.",
    "af": "Geen netwerktoestande nie.",
    "ak": "Éyì wò ɖi àwòrà.",
    "am": "የኔትዎርክ ሁኔታ የለውም።",
    "an": "No hai condizions de ret.",
    "ar": "لا توجد ظروف الشبكة.",
    "as": "নেটওয়াৰ্কৰ স্থিতি নাই।",
    "av": "Нетка сетков абарол.",
    "ay": "Mana lurañaniwi.",
    "az": "Şəbəkə şəraiti yoxdur.",
    "ba": "Бүлек теләгеҙлектәр юҡ.",
    "be": "Няма сеткавых умоў.",
    "bg": "Няма мрежови условия.",
    "bh": "नेटवर्क अवस्थाएँ नहीं हैं।",
    "bi": "No garemwan netwok.",
    "bm": "Màn wala netwɔkùnèɛ.",
    "bn": "কোনো নেটওয়ার্ক শর্ত নেই।",
    "bo": "ལོ་ནུབ་བཀོད་པའི་གནས་ཞུ་མེད།",
    "br": "Dre vrezoniezhioù.",
    "bs": "Nema mrežnih uslova.",
    "ca": "No hi ha condicions de xarxa.",
    "ce": "Къовза шартанан ла аьцгьаро.",
    "ch": "Ti ainimwa si network.",
    "co": "Nisuna cundizzione di rete.",
    "cr": "ᓂᓈᑦᑕᕐᑭᐙᓂᓂᑦᓯ.",
    "cs": "Nejsou síťové podmínky.",
    "cu": "Нѣсть мрєжевъ стани.",
    "cv": "Çĕрле сетлĕх кăтала патшалӳ.",
    "cy": "Dim amodau rhwydwaith.",
    "da": "Ingen netværksforhold.",
    "de": "Keine Netzwerkbedingungen.",
    "dv": "މިހާން އެނބުރުތަކަށް ނެތްބެލެވެ.",
    "dz": "ངོ་སྤྲོད་གནས་ཞུ་མེད།",
    "ee": "Ɖɔ adan network.",
    "el": "Δεν υπάρχουν δικτυακές συνθήκες.",
    "en": "No network conditions.",
    "eo": "Neniu retkondiĉoj.",
    "es": "No hay condiciones de red.",
    "et": "Võrgutingimusi pole.",
    "eu": "Ez dago sarea baldintzarik.",
    "fa": "شرایط شبکه وجود ندارد.",
    "ff": "Noppin ko yaa network.",
    "fi": "Ei verkkoyhteyksiä.",
    "fj": "E sega na veiyawaki interneti.",
    "fo": "Eingin nettverksundantøki.",
    "fr": "Pas de conditions réseau.",
    "fy": "Gjin netwurkfoarwaarden.",
    "ga": "Gan coinníollacha líonra.",
    "gd": "Gun àbhaisteachd làn-rèidiochd.",
    "gl": "Sen condicións de rede.",
    "gn": "Ñomongeta jave ojejapirû.",
    "gu": "કોઈ નેટવર્ક શરતો નથી.",
    "gv": "Cha nel co-lhieeaghtyn raaft.",
    "ha": "Babu magancewas suwaye.",
    "he": "אין תנאי רשת.",
    "hi": "कोई नेटवर्क शर्तें नहीं हैं।",
    "ho": "Aikomau aibira network.",
    "hr": "Nema mrežnih uvjeta.",
    "ht": "Pa gen kondisyon nan rezo a.",
    "hu": "Nincsenek hálózati feltételek.",
    "hy": "Ոչ մի ցանկացած ցանցային պայմանները:",
    "hz": "Kumbe kunyi na intaniti.",
    "ia": "Nulle conditiones de reticulo.",
    "id": "Tidak ada kondisi jaringan.",
    "ie": "Nul conditiones de rete.",
    "ig": "Enyịnetwork kụzụ ojọọ.",
    "ii": "ꂵꏒꏓꐯꏹꏫꏕ.",
    "ik": "Ćeh nihiqatii.",
    "io": "Nula ret-kondicioni.",
    "is": "Engar netjaáskorðar.",
    "it": "Nessuna condizione di rete.",
    "iu": "ᐊᒐᔪᖅᑯᓯᖏᑦ ᓴᕆᓴᒃᑦᓯᒪᔪᑦᑦᓯ.",
    "ja": "ネットワーク条件なし。",
    "jv": "Ora ana kondisi jaringan.",
    "ka": "ქსელის პირობები არ არის.",
    "kg": "Ezali réseau.",
    "ki": "No network rũrĩ.",
    "kj": "Aongomita umbwa.",
    "kk": "Желілердің шарттары жоқ.",
    "kl": "Tulut netværk.",
    "km": "មិនមានលក្ខខណ្ឌបណ្តាញ។",
    "kn": "ನೆಟ್ವರ್ಕ್ ಶರತ್ವುಗಳು ಇಲ್ಲ.",
    "ko": "네트워크 조건 없음.",
    "kr": "Ba ta gamsu jaringan.",
    "ks": "وچونو وضاحت نه.",
    "ku": "Tiştên têkildarî têkildarî tune ne.",
    "kv": "Нету мережовши.",
    "kw": "Nyns yw kondisiyonnow resek.",
    "ky": "Кабаттар жок.",
    "la": "Nullae condicionae retis.",
    "lb": "Keng Netzwierkbedingunge.",
    "lg": "Teyandikira interneti.",
    "li": "Geej netwerkveurwaarde.",
    "ln": "Ezali kokokomatisa yango ezalaka.",
    "lo": "ບໍ່ມີສັນຕິພາບເວີ.",
    "lt": "Nėra tinklo sąlygų.",
    "lu": "Ba yo umbwa wa network.",
    "lv": "Nav tīkla nosacījumu.",
    "mg": "Tsy misy toe-tsaina ny pejy.",
    "mh": "Bukot ne-tinikinik.",
    "mi": "He whanaketanga whatunga kore.",
    "mk": "Нема мрежни услови.",
    "ml": "നെറ്റ്‌വർക്ക് സാന്നിദ്ധ്യങ്ങൾ ഇല്ല.",
    "mn": "Сүлжээний нөөц байхгүй.",
    "mr": "कोणत्याही नेटवर्क अवस्था नाही.",
    "ms": "Tiada syarat rangkaian.",
    "mt": "M'hemmx kundizzjonijiet tan-netwerk.",
    "my": "ကွန်ယက်အခြေအနေမရှိပါ။",
    "na": "No network situations.",
    "nb": "Ingen nettverksforhold.",
    "nd": "Akukho amakhasimende nekhaya.",
    "ne": "कुनै नेटवर्क स्थिति छैन।",
    "ng": "Ngeji network.",
    "nl": "Geen netwerkcondities.",
    "nn": "Ingen nettverksforhold.",
    "no": "Ingen nettverksforhold.",
    "nr": "Akukho amakhasimende nekhaya.",
    "nv": "Hózhǫǫji nízhóníígíí.",
    "ny": "Pasavuta network.",
    "oc": "Pas de condicions de ret.",
    "oj": "Awakaadendaawaa jibwaawaa.",
    "om": "Lakkawwan network.",
    "or": "କୋଣଟି ନେଟଓଆର୍କ ଶର୍ତ ନାହିଁ।",
    "os": "Без сети рамзони.",
    "pa": "ਕੋਈ ਨੈਟਵਰਕ ਸਥਿਤੀ ਨਹੀਂ ਹੈ।",
    "pi": "नेटवर्क स्थितियों नहीं है।",
    "pl": "Brak warunków sieciowych.",
    "ps": "چا نه د شبکې شرایط هلې نشته.",
    "pt": "Sem condições de rede.",
    "qu": "Mana intinetka llaqsiy.",
    "rm": "Nagut stadi da la ret.",
    "rn": "Ntikurane network.",
    "ro": "Nu există condiții de rețea.",
    "ru": "Нет сетевых условий.",
    "rw": "Nta byaba bikwiye ku buringanyi.",
    "sa": "किमपि नेट्वर्क स्थितिः नास्ति।",
    "sc": "No hat konditzionis de rete.",
    "sd": "ڪوئي نيٽ ورڪ حالت ناهي آهي.",
    "se": "Ei olbmotvuođđu juogaheami.",
    "sg": "Tî kô kôzâ yandêlê môyâ yê.",
    "si": "ජාලය වෙනුවෙන් කෙරේද?",
    "sk": "Žiadne sieťové podmienky.",
    "sl": "Ni omrežnih pogojev.",
    "sm": "Leai ni itu faiga o le neti.",
    "sn": "Hauna marirosi emumaindiro.",
    "so": "Ma jiro shuruudooyin network.",
    "sq": "Nuk ka kushte rrjeti.",
    "sr": "Нема мрежних услова.",
    "ss": "Asikho izimo zekhaya.",
    "st": "Ha ho le amotho ea network.",
    "su": "Teu ayana kondisi jaringan.",
    "sv": "Inga nätverksvillkor.",
    "sw": "Hakuna hali ya mtandao.",
    "ta": "பிணைய சீர்புகள் இல்லை.",
    "te": "సంజ్ఞ నెట్వర్క్ లేదు.",
    "tg": "Шартҳои шабака ёфт нашудааст.",
    "th": "ไม่มีเงื่อนไขเครือข่าย",
    "ti": "ምንም ዕልት ብምኽንያት ኣይፈትልን።",
    "tk": "Internetiň şertleriniň ýok.",
    "tl": "Walang kundisyon sa network.",
    "tn": "Ha ho le amotho ea network.",
    "to": "ʻIkai ha fakakaukau fakafonua.",
    "tr": "Ağ koşulu yok.",
    "ts": "Asikho izimo zekhaya.",
    "tt": "İnternet şertlawı yuq.",
    "tw": "Tee nkrataa bɔ mu.",
    "ty": "Aucune condition réseau.",
    "ug": "تور دائمىيىلىكى يوق.",
    "uk": "Немає мережевих умов.",
    "ur": "کوئی نیٹ ورک حالات نہیں ہیں۔",
    "uz": "Tarmoq shartlari yo'q.",
    "ve": "Huna marirosi emumaindiro.",
    "vi": "Không có điều kiện mạng.",
    "vo": "Nul network konditioni.",
    "wa": "Nén a gnou condicions do rôze.",
    "wo": "Nopp naay condition réseau.",
    "xh": "Akukho amaxabiso okuqukethweyo.",
    "yi": "קיין נעטוואַרק בדינות.",
    "yo": "Kò sí ẹ̀tọ́ ọrọ́ àpapọ́ nínú àwọn nẹ́tíwọ̀kì.",
    "za": "没有网络条件。",
    "zh": "没有网络条件。",
    "zu": "Akekhona izimo zethu zomthandazo.",
]

