import Foundation

func getTitle() -> String {
    let randomIndex = Int.random(in: 0..<topArticles.count)
    return topArticles[randomIndex]
}

let topArticles = [
    "2003 invasion of Iraq",
    "2004 Indian Ocean earthquake and tsunami",
    "2010 FIFA World Cup",
    "2011 Tōhoku earthquake and tsunami",
    "2012 Summer Olympics",
    "2014 FIFA World Cup",
    "2016 Summer Olympics",
    "2016 United States presidential election",
    "2018 FIFA World Cup",
    "2020 Summer Olympics",
    "2020 United States presidential election",
    "2022 FIFA World Cup",
    "2022 Russian invasion of Ukraine",
    "A Brief History of Time",
    "A Game of Thrones",
    "A Song of Ice and Fire",
    "A.C. Milan",
    "ABBA",
    "AC/DC",
    "Abraham",
    "Abraham Lincoln",
    "Academy Awards",
    "Adele",
    "Adolf Hitler",
    "Africa",
    "Albert Einstein",
    "Albus Dumbledore",
    "Alexander Hamilton",
    "Alexander the Great",
    "Alfred the Great",
    "Alice's Adventures in Wonderland",
    "Alpha Centauri",
    "Amazon River",
    "American Civil War",
    "American Horror Story",
    "American Revolutionary War",
    "Americas",
    "Among Us",
    "Andromeda Galaxy",
    "Angelina Jolie",
    "Animal",
    "Animal Farm",
    "Antarctica",
    "Apollo",
    "Apple",
    "Argentina national football team",
    "Ariana Grande",
    "Aristotle",
    "Arnold Schwarzenegger",
    "Arsenal F.C.",
    "Ashoka",
    "Asia",
    "Aston Villa F.C.",
    "Atlantic Ocean",
    "Atomic bombings of Hiroshima and Nagasaki",
    "Attack on Pearl Harbor",
    "Augustus",
    "Australia",
    "Avatar",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "BTS",
    "Backstreet Boys",
    "Balkans",
    "Barack Obama",
    "Barron Trump",
    "Batman",
    "Batman: Arkham Knight",
    "Battle for France",
    "Battle of Britain",
    "Battle of Dunkirk",
    "Battle of Midway",
    "Battle of Stalingrad",
    "Battle of Waterloo",
    "Battle of the Bulge",
    "Bear",
    "Bee Gees",
    "Bermuda Triangle",
    "Beyoncé",
    "Bhad Bhabie",
    "Bible",
    "Big Bang",
    "Bill Clinton",
    "Bill Gates",
    "Billie Eilish",
    "Bird",
    "Black Death",
    "Black hole",
    "Blue Ocean Strategy",
    "Bob Marley",
    "Borussia Dortmund",
    "Bosnian War",
    "Boxer Rebellion",
    "Brad Pitt",
    "Brave New World",
    "Brazil national football team",
    "Breaking Bad",
    "Britney Spears",
    "Brock Lesnar",
    "Bruce Lee",
    "COVID-19 pandemic",
    "Caitlyn Jenner",
    "Caligula",
    "Canada",
    "Canary Islands",
    "Captain America",
    "Carol Danvers",
    "Cat",
    "Cattle",
    "Ceres (dwarf planet)",
    "Charlemagne",
    "Charles III",
    "Charles Manson",
    "Charli D'Amelio",
    "Cheetah",
    "Chelsea F.C.",
    "Chernobyl disaster",
    "Chicken",
    "China",
    "Chupacabra",
    "Clash of Civilizations",
    "Cleopatra",
    "Climate change",
    "Clint Eastwood",
    "Code Geass",
    "Cold War",
    "Coldplay",
    "Columbine High School massacre",
    "Confucius",
    "Conor McGregor",
    "Continent",
    "Coronavirus",
    "Cougar",
    "Creative Commons Attribution",
    "Crimea",
    "Crimean War",
    "Cristiano Ronaldo",
    "Crusades",
    "Cthulhu",
    "Cyberpunk 2077",
    "Daft Punk",
    "Dark energy",
    "Dark matter",
    "Darth Vader",
    "Das Kapital",
    "David",
    "David Beckham",
    "David Bowie",
    "Deadpool",
    "Death Stranding",
    "Demi Lovato",
    "Design Patterns",
    "Dexter",
    "Diana, Princess of Wales",
    "Dinosaur",
    "Doctor Strange",
    "Doctor Who",
    "Dodo",
    "Dog",
    "Dolphin",
    "Don Quixote",
    "Donald Trump",
    "Doppelgänger",
    "Dracula",
    "Dragon",
    "Dune",
    "Dunkirk evacuation",
    "Dwayne Johnson",
    "Earth",
    "Earthquake",
    "Eclipse",
    "Edward VIII",
    "Elephant",
    "Elizabeth I",
    "Elizabeth II",
    "Elon Musk",
    "Elvis Presley",
    "Eminem",
    "Emma Raducanu",
    "Emma Watson",
    "England national football team",
    "Erling Haaland",
    "Event horizon",
    "Evolution",
    "Exo",
    "FC Barcelona",
    "FC Bayern Munich",
    "Facebook",
    "Falklands War",
    "Fallout 4",
    "Family Guy",
    "Fifty Shades of Grey",
    "Final Fantasy XV",
    "Finn Wolfhard",
    "Fleetwood Mac",
    "Flying Spaghetti Monster",
    "Foo Fighters",
    "Foundations of Geopolitics",
    "France",
    "France national football team",
    "Frankenstein",
    "Franklin D. Roosevelt",
    "Freakonomics",
    "Freddie Mercury",
    "French Revolution",
    "French and Indian War",
    "Friends",
    "Galaxy",
    "Game of Thrones",
    "Ganges",
    "Gaten Matarazzo",
    "Gautama Buddha",
    "Genghis Khan",
    "George H. W. Bush",
    "George VI",
    "George W. Bush",
    "George Washington",
    "Germany",
    "Germany national football team",
    "Getting Things Done",
    "Giraffe",
    "Girls' Generation",
    "Glee",
    "God",
    "God of War (2018 video game)",
    "Godzilla",
    "Golden State Warriors",
    "Google",
    "Gorillaz",
    "Grand Canyon",
    "Grand Theft Auto IV",
    "Grand Theft Auto V",
    "Grand Theft Auto: San Andreas",
    "Gray's Anatomy",
    "Great Depression",
    "Green Bay Packers",
    "Green Day",
    "Greta Thunberg",
    "Grey's Anatomy",
    "Guerrilla marketing",
    "Gulf War",
    "Guns N' Roses",
    "Guns, Germs, and Steel",
    "Halley's Comet",
    "Hannibal",
    "Harley Quinn",
    "Harry Potter",
    "Harry Potter and the Deathly Hallows",
    "Heath Ledger",
    "Henry V of England",
    "Henry VIII",
    "Henry VIII of England",
    "High School DxD",
    "Himalayas",
    "Horizon Zero Dawn",
    "Horse",
    "House",
    "How I Met Your Mother",
    "How to Win Friends and Influence People",
    "Human",
    "Hundred Years' War",
    "Hurricane Katrina",
    "Ice Age",
    "India",
    "Indian Rebellion of 1857",
    "Industrial Revolution",
    "Inferno",
    "Inter Milan",
    "Iran–Iraq War",
    "Iraq War",
    "Iron Maiden",
    "Iron Man",
    "Isabela Merced",
    "Israel",
    "Israeli–Palestinian conflict",
    "It",
    "Italy national football team",
    "Jackie Evancho",
    "Jacob Tremblay",
    "Jadon Sancho",
    "Jaguar",
    "James, Viscount Severn",
    "Japan",
    "Jay-Z",
    "Jeffrey Dahmer",
    "Jenna Ortega",
    "Jennifer Aniston",
    "Jennifer Lawrence",
    "Jennifer Lopez",
    "Jessica Jones",
    "Jesus",
    "Joan of Arc",
    "Joe Biden",
    "John Cena",
    "John F. Kennedy",
    "John Lennon",
    "Johnny Depp",
    "Jojo Siwa",
    "Jonas Brothers",
    "Joseph Stalin",
    "Journey to the Center of the Earth",
    "Julius Caesar",
    "Jupiter",
    "Justin Bieber",
    "Juventus F.C.",
    "Kama Sutra",
    "Kamala Harris",
    "Kanye West",
    "Kargil War",
    "Katy Perry",
    "Keanu Reeves",
    "Kepler's Supernova",
    "Kim Kardashian",
    "King Arthur",
    "Kiss",
    "Kobe Bryant",
    "Korean War",
    "Kosovo War",
    "Krishna",
    "Kristen Stewart",
    "LaMelo Ball",
    "Lady Gaga",
    "Lady Louise Windsor",
    "Lali Espósito",
    "LeBron James",
    "League of Legends",
    "Led Zeppelin",
    "Leicester F.C.",
    "Leonardo DiCaprio",
    "Leonardo da Vinci",
    "Les Misérables",
    "Leviathan",
    "Lightning",
    "Lil Pump",
    "Lil Wayne",
    "Linkin Park",
    "Lion",
    "Lionel Messi",
    "Liverpool F.C.",
    "Lolita",
    "Long Island",
    "Lord Voldemort",
    "Los Angeles Lakers",
    "Lost",
    "Luke Cage",
    "Lunar eclipse",
    "Mackenzie Foy",
    "Maddie Ziegler",
    "Madonna",
    "Magna Carta",
    "Mahatma Gandhi",
    "Maize",
    "Malware",
    "Mammal",
    "Manchester City F.C.",
    "Manchester United F.C.",
    "Manny Pacquiao",
    "Marco Polo",
    "Marcus Aurelius",
    "Margaret Thatcher",
    "Mariah Carey",
    "Marilyn Monroe",
    "Mario",
    "Mark Wahlberg",
    "Mark Zuckerberg",
    "Mars",
    "Mckenna Grace",
    "Megan Fox",
    "Meghan Markle",
    "Meghan, Duchess of Sussex",
    "Mein Kampf",
    "Men Are from Mars, Women Are from Venus",
    "Mercury (planet)",
    "Metal Gear Solid V: The Phantom Pain",
    "Metallica",
    "Mexican–American War",
    "Michael Jackson",
    "Michael Jordan",
    "Michael Oher",
    "Michael Phelps",
    "Mickey Mouse",
    "Mike Tyson",
    "Mila Kunis",
    "Miley Cyrus",
    "Milky Way",
    "Millie Bobby Brown",
    "Minecraft",
    "Mississippi",
    "Modern Family",
    "Moon",
    "Moses",
    "Mount Everest",
    "Muhammad",
    "Muhammad Ali",
    "N.W.A",
    "NCIS",
    "Napoleonic Wars",
    "Naruto",
    "Natalie Portman",
    "Nelson Mandela",
    "Neptune",
    "Nero",
    "New England Patriots",
    "New York City",
    "New York Yankees",
    "Newcastle United F.C.",
    "Neymar",
    "Nicki Minaj",
    "Nile",
    "Nineteen Eighty-Four",
    "Nirvana",
    "No Man's Sky",
    "Noah Cyrus",
    "Normandy landings",
    "North America",
    "Novak Djokovic",
    "O. J. Simpson",
    "Ocean",
    "Octopus",
    "Olivia Rodrigo",
    "On the Origin of Species",
    "One Direction",
    "Outliers",
    "Pablo Escobar",
    "Pacific Ocean",
    "Palau",
    "Paris Saint-Germain F.C.",
    "Persona 5",
    "Peyton Manning",
    "Photosynthesis",
    "Pink Floyd",
    "Plato",
    "Platypus",
    "Pluto",
    "Pokémon Go",
    "Polar bear",
    "Pop Smoke",
    "Potato",
    "Pride and Prejudice",
    "Prince",
    "Prince (musician)",
    "Prince George of Cambridge",
    "Prince Philip, Duke of Edinburgh",
    "Princess Charlotte of Cambridge",
    "Princess Margaret, Countess of Snowdon",
    "Prometheus",
    "Queen",
    "Queen Victoria",
    "Rabbit",
    "Raccoon",
    "Rafael Nadal",
    "Ragnar Lodbrok",
    "Rangers F.C.",
    "Real Madrid C.F.",
    "Red Dead Redemption",
    "Red Dead Redemption 2",
    "Red Hot Chili Peppers",
    "Resident Evil 7: Biohazard",
    "Rich Dad Poor Dad",
    "Rihanna",
    "Robin Hood",
    "Robin Williams",
    "Roblox",
    "Roger Federer",
    "Ronald Reagan",
    "Ronaldinho",
    "Ronaldo",
    "Ronda Rousey",
    "Russia",
    "Russo-Ukrainian War",
    "Ryan Reynolds",
    "Sachin Tendulkar",
    "Santa Claus",
    "Sapiens: A Brief History of Humankind",
    "Satan",
    "Saturn",
    "Scarlett Johansson",
    "Search engine",
    "Second Boer War",
    "Selena Gomez",
    "September 11 attacks",
    "Serena Williams",
    "Sex",
    "Shaquille O'Neal",
    "Shark",
    "Sherlock",
    "Silent Spring",
    "Singapore",
    "Sirius",
    "Six-Day War",
    "Skathi (moon)",
    "Slipknot",
    "Snake",
    "Snoop Dogg",
    "Socrates",
    "Solar System",
    "Solar eclipse",
    "Sons of Anarchy",
    "South America",
    "Soviet-Afghan War",
    "Spain national football team",
    "Spanish Civil War",
    "Spanish flu",
    "Spartacus",
    "Spice Girls",
    "Spider",
    "Spider-Man",
    "Star Wars",
    "Stephen Curry",
    "Stephen Hawking",
    "Steve Jobs",
    "Stranger Things",
    "Sun",
    "Supernovae",
    "Sword Art Online",
    "Sylvester Stallone",
    "Syrian civil war",
    "Taylor Swift",
    "Ted Bundy",
    "Thanos",
    "The 48 Laws of Power",
    "The 7 Habits of Highly Effective People",
    "The Art of War",
    "The Avengers",
    "The Beatles",
    "The Bell Curve",
    "The Big Bang Theory",
    "The Big Short",
    "The Catcher in the Rye",
    "The Communist Manifesto",
    "The Dark Knight Rises",
    "The Elder Scrolls V: Skyrim",
    "The Girl with the Dragon Tattoo",
    "The Great Gatsby",
    "The Handmaid's Tale",
    "The Hobbit",
    "The Holocaust",
    "The Hunger Games",
    "The Last of Us",
    "The Last of Us Part II",
    "The Legend of Zelda: Breath of the Wild",
    "The Lord of the Rings",
    "The Picture of Dorian Gray",
    "The Prince",
    "The Rolling Stones",
    "The Simpsons",
    "The Tipping Point",
    "The Troubles",
    "The Undertaker",
    "The Vampire Diaries",
    "The Walking Dead",
    "The Walking Dead (TV series)",
    "The Wealth of Nations",
    "The Winds of Winter",
    "The Witcher 3: Wild Hunt",
    "The World Is Flat",
    "Think and Grow Rich",
    "Thor",
    "Tiger",
    "Tiger Woods",
    "Titan (moon)",
    "Titanic",
    "To Kill a Mockingbird",
    "Tom Brady",
    "Tom Cruise",
    "Tom Hanks",
    "Tom Hardy",
    "Tomato",
    "Tottenham Hotspur F.C.",
    "Triple H",
    "Trojan War",
    "Tsunami",
    "Tupac Shakur",
    "Turmeric",
    "Tutankhamun",
    "Tyrannosaurus",
    "UEFA Euro 2020",
    "United Kingdom",
    "United States",
    "Universe",
    "Until Dawn",
    "Uranus",
    "Usain Bolt",
    "Vampire",
    "Venus",
    "Vietnam War",
    "Virat Kohli",
    "Virus",
    "Vladimir Putin",
    "Volcano",
    "War in Afghanistan (2001–2021)",
    "War of 1812",
    "Watchmen",
    "Wayne Rooney",
    "West Ham United F.C.",
    "Who Moved My Cheese?",
    "Wikipedia",
    "Will Smith",
    "William Shakespeare",
    "William Wallace",
    "William the Conqueror",
    "Willow Smith",
    "Winston Churchill",
    "Winter War",
    "Winter solstice",
    "Wonder Woman",
    "World War I",
    "World War II",
    "World of Warcraft",
    "X-Men: Evolution",
    "XXXX",
    "Yara Shahidi",
    "Yellowstone National Park",
    "Yom Kippur War",
    "YouTube",
    "Zion Williamson",
    "Zlatan Ibrahimovic",
    "xHamster"
]
