# fly.toml app configuration file generated for vocode-react-demo on 2023-10-13T15:24:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vocode-react-demo"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
