# fly.toml app configuration file generated for voice-webapp on 2023-10-13T15:44:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "voice-webapp"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
